name = "GeneralizedSasakiNakamura"
uuid = "7d2aac85-6cc1-40c7-a4aa-e1a43f13f131"
authors = ["Rico Ka Lok Lo"]
version = "0.5.2"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpinWeightedSpheroidalHarmonics = "680e17a6-2a17-48fd-ae01-e2b5a643bef0"
TaylorSeries = "6aa5eb33-94cf-58f4-a9d0-e4b2c4fc25ea"

[compat]
DifferentialEquations = "7"
ForwardDiff = "^0.10"
Interpolations = "^0.15"
Roots = "2"
SpinWeightedSpheroidalHarmonics = "^1"
TaylorSeries = "^0.18"
HypergeometricFunctions = "^0.3.23"
julia = "^1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
